### PR TITLE
Fix a typo in command : D

### PR DESCRIPTION
**Pull request by opabravo**
Fix a typo in command: `socks5h` -> `socks5`

### CODE REVIEW

**Comment by CalfCrusher** [comment]
Hello opabravo, this is not a typo, **SOCKS5** differs from **SOCKS5h**: with SOCKS5h, when the client wants to establish a connection with a remote host, it sends the domain name to the SOCKS5h proxy server instead of the IP address. I know that using TOR as socks proxy the IP specified is always 127.0.0.1 BUT if you want use another socks and not TOR, you can use a domain name instead than IP. **SOCKS5h** can potentially help prevent **DNS leaks** compared to **SOCKS5**. Anyway thanks and have a nice day ;)

**Comment by opabravo** [comment]
Cool, didn't know that's a thing, thanks for letting me know!

**Comment by opabravo** [comment]
> Hello opabravo, this is not a typo, **SOCKS5** differs from **SOCKS5h**: with SOCKS5h, when the client wants to establish a connection with a remote host, it sends the domain name to the SOCKS5h proxy server instead of the IP address. I know that using TOR as socks proxy the IP specified is always 127.0.0.1 BUT if you want use another socks and not TOR, you can use a domain name instead than IP. **SOCKS5h** can potentially help prevent **DNS leaks** compared to **SOCKS5**. Anyway thanks and have a nice day ;)

Cool, didn't know that's a thing, thanks for your excellent explanation!

**Comment by CalfCrusher** [comment]
You welcome !

**Pull request closed without merging**
